### ISSUE TITLE
NPM install not working with new version of jkroso/type 

### ISSUE THREAD

**Issue by markeySorenson** [jkroso/equals#10]
Good morning,

Just tried to install this package using **npm install equals** and I get the error **user not allowed to access it : @jkroso/type**. I noticed that the repository jkroso/type changed in the past 24 hours and wondered if it was the cause of the issue.

I would appreciate if you could look into the issue, as it is a dependancy of one of our modules.

Many thanks,

Richard

**Comment by jkroso** [comment]
I just did a normal `npm publish` so if permissions changed then thats weird. It works for me though so I can't help you figure out the issue

**Comment by markeySorenson** [comment]
Thank you for looking into it.

The error was first noticed due to our AWS (Amazon Web Services) CI server
not installing the package cancan (on default node.js settings). Then I
tried it locally and drilled it down to that message.

I then got a few of my colleagues and someone external to try it with the
same result.

It could be the case that the PR someone else has raised fixes the issue.

**Comment by markeySorenson** [comment]
Changed our build agent from node version 0.10.29 to a newer version and it's working now.
