### ISSUE TITLE
Does not work with node.js 0.10

### ISSUE THREAD

**Issue by whizkid77** [jkroso/equals#7]
The dependency on module jkroso-type has some ES6 usage of Map and Set, which node.js does not support.

If Map and Set have not been polyfilled, an error occurs:
ReferenceError: Map is not defined
at type (jkroso-type/index.js:20:22)

**Comment by jkroso** [comment]
The latest node has both those. I guess I should update the "engine" metadata

**Comment by whizkid77** [comment]
Ahh you're right.  Thanks for the quick reply.  Closing issue.
