### ISSUE TITLE
Why is a function named memoGaurd() ?

### ISSUE THREAD

**Issue by romainbessugesmeusy** [jkroso/equals#8]
Hey there, it's not an issue !

I was wondering if "gaurd" had a meaning or if it was only the verb "guard" misspelled.

Thank you for this helpful dependency.

**Comment by jkroso** [comment]
Yea its just a misspelling. If you invent any math please don't name it after yourself. I'd never be able to spell it. :smile:

**Comment by romainbessugesmeusy** [comment]
Aha ;-) Thanks for the answer
